### ISSUE TITLE
NPM install doesn't work?

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/victory-bar#12]
From @exogen 

So `victory-animation` and others are using this workflow now, but it doesn't seem to work – install fails with versions of npm < 3. I think we may need to bring back `prepublish`, but make it just build `lib` and not `dist` (like we do in the new `postinstall`).

Here's what happens when you run `npm install` in a fresh `victory-bar` working copy:

```
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.0","npm":"2.14.8"})
npm WARN peerDependencies The peer dependency file-loader@* included from url-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> victory-animation@0.0.6 postinstall /Users/brianbeck/Projects/Formidable/victory-bar/node_modules/victory-animation
> npm run build-lib

|
> victory-animation@0.0.6 build-lib /Users/brianbeck/Projects/Formidable/victory-bar/node_modules/victory-animation
> npm run clean-lib && babel --stage 0 src -d lib

\
> victory-animation@0.0.6 clean-lib /Users/brianbeck/Projects/Formidable/victory-bar/node_modules/victory-animation
> rimraf lib

sh: rimraf: command not found
```

Note that `victory-bar` and Node v4 are not the culprits – `victory-animation` and npm v2 are.

**Comment by ryan-roemer** [comment]
@exogen -- We didn't "take away `prePublish`" we just replaced it with `preversion`. The `postinstall` build follows Radium and is needed for git installs of Radium and presumably these repos if we want them.

Can you propose a strawman PR in this repo (we don't merge it) of what you think we _should_ move to instead? (So I can better understand what's going on?)

/cc @alexlande @boygirl

**Comment by exogen** [comment]
Opened one on the boilerplate too as I assume we'll be changing that: FormidableLabs/formidable-react-component-boilerplate#49

**Comment by ryan-roemer** [comment]
@exogen -- Reading your above error, it looks like `victory-animation`'s `postinstall` is running **before** the install is finished (hence `rimraf` isn't available).

1. If you re-run the root `npm install` does it pass?
2. Have you googled for this specific issue? (Because that's what I'm doing -- I have a similar error to yours in `victory-animation`, but it's `babel` that's missing until I install twice).

I very much doubt this is an issue with the boilerplate or our approach, but rather something is fishy with NPM...

**Comment by ryan-roemer** [comment]
Hmm... We are actually doing it differently than Radium -- Radium _does_ add `lib` to what's published to NPM. And then does a detect to see if lib isn't there before installing.

This is probably how Radium sidesteps the issue. @exogen --  I'm fine if you or @boygirl want to follow the exact Radium heuristic of also publishing `lib` in addition to `dist` and adding the protection string `node -e \"require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})\"` to our `postinstall` command like Radium does...

**Comment by exogen** [comment]
@ryan-roemer: :+1: Arrived at the same conclusion, going to fiddle with it for a few more minutes but will most likely copy Radium's approach.
