### ISSUE TITLE
audit tags / npm versions

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory-bar#49]
make sure there is a tag for every npm version

**Comment by boygirl** [comment]
npm versions:
`['0.1.0', '1.0.0', '1.0.1', '1.0.2', '1.0.3', '2.0.0', '2.1.0', '2.2.0', '2.2.2', '2.2.3', '2.3.0', '2.4.0', '2.4.1', '2.4.2', '2.4.3', '2.4.4']`

tags:
`v0.1.0 v1.0.0 v1.0.1 v1.0.2 v2.0.0 v2.1.0 v2.2.0 v2.2.2 v2.2.3 v2.3.0 v2.4.0 v2.4.1 v2.4.2 v2.4.3 v2.4.4`

missing tags: `v1.0.3`

**Comment by coopy** [comment]
Add a list of repos with
- [ ]

**Comment by boygirl** [comment]
Closing since this repo is being merged into [VictoryChart](https://github.com/formidablelabs/victory-chart)
