### ISSUE TITLE
Bar chart dependent axis should include zero by default

### ISSUE THREAD

**Issue by dandelany** [FormidableLabs/victory-bar#75]
A good rule of thumb is that bar charts should always include zero on the dependent axis, [for the reasons discussed in this article](https://flowingdata.com/2015/08/31/bar-chart-baselines-start-at-zero/). It should still be possible to set a custom domain via the `domain` prop, but the default domain should include zero.

For example, see this JSFiddle: https://jsfiddle.net/tzqd66ys/

**Comment by knowbody** [comment]
that's a very good point IMO, thanks for that! @dandelany mind sending a PR?

**Comment by dandelany** [comment]
After looking into it, this turns out to be a bit trickier than expected to implement. I updated the VictoryBar getDomain method to include zero, which works for VictoryBar components on their own. However, when used inside of a VictoryChart, the VictoryChart determines the domain, and still uses the old method. I would have to update the VictoryChart getDomain method to "know" about bar charts and include zero if one of the children is a bar chart.

I'm going to talk to @boygirl this week about some architecture ideas that would make this easier to implement before moving forward on this.
