### ISSUE TITLE
Horizontal bar chart dependent X-axis backwards

### ISSUE THREAD

**Issue by dandelany** [FormidableLabs/victory-bar#76]
When plotting numerical values on a horizontal bar chart within a `VictoryChart`, the X-axis is backwards from expected. [Here's a JSFiddle test case](https://jsfiddle.net/dandelany/yjjr4wb9/).

![image](https://cloud.githubusercontent.com/assets/734221/12073212/a419285c-b0df-11e5-9e6a-baf36f448c8e.png)

**Comment by dandelany** [comment]
Actually it looks like horizontal bars are more broken than I thought - the Y-axis labels are in the correct order but the data bars are actually in reverse order, and the length of the bars is actually correct but the x-axis is labeled backwards on the VictoryChart -  [see this test case](https://jsfiddle.net/dandelany/ypvyz51g/). By random luck, in my last test case, these two bugs cancelled each other out and made it look like a different bug entirely.

Looking into a fix...

**Comment by dandelany** [comment]
Fixed the ordering issue above with #77, but the axis label order is still an issue, likely in victory-charts. Will take a look.

**Comment by boygirl** [comment]
Closing in favor of more general issue in victory-chart https://github.com/FormidableLabs/victory-chart/issues/36
