### ISSUE TITLE
labels for individual bars

### ISSUE THREAD

**Issue by topheman** [FormidableLabs/victory-bar#81]
Is it possible to set different color for each bar on a `VictoryBar` ? I tried `dataAttributes`, but it seems to be only when you have "groups" of bars and I still want to be able to set a label above them.

Use case: https://topheman.github.io/d3-react-experiments/#/victory-world-population-by-age-range

Would be great to have the same color for the year range on each charts (maybe it needs an other approach).

**Comment by boygirl** [comment]
Hi there! You should be able to dump attributes like `fill`directly into the data object like so:

```
<VictoryBar
  data={[
      {x: 1, y: 1, fill: "tomato", width: 30},
      {x: 2, y: 2, fill: "orange", width: 20},
      {x: 3, y: 3, fill: "gold", width: 10},
      {x: 4, y: 4, fill: "turquoise",  width: 5}
    ]}
 />
```
You're right about the labels though. They should operate the same way, for single series of bars, but I overlooked that. Do you mind if I change the title of this issue to something like "Support labels on each bar"

**Comment by topheman** [comment]
>Do you mind if I change the title of this issue to something like "Support labels on each bar"

Please do @boygirl 

I'll check your solution tomorrow (it's past 1a.m. in Paris 😴) and I let you know.

**Comment by knowbody** [comment]
@topheman here you go: https://jsbin.com/luwazovuda/edit?js,output

**Comment by knowbody** [comment]
Resolved by @boygirl so closing.

**Comment by boygirl** [comment]
The issue also refers to problem with individual bar labels, so I've just changed the title.

**Comment by Juli0GT** [comment]
Hi boy girl, where can I find an example about how dataAttributes work? I'm trying to style my bars depending on its x value. If x < 4 one color, if x>=4 a different color.

```
            <VictoryBar
              data={[
                {
                  x: (x) => x < 4,
                  stroke: "url(#gradient2)",
                  fill: "url(#gradient2)",
                  opacity: (0.5)
                },
                {
                  x: (x) => x >= 4,
                  stroke: "url(#gradient1)",
                  fill: "url(#gradient1)",
                }
              ]}
              style={{
                data: {
                  fill: (d) => d.fill,
                  opacity: (d) => d.opacity
                }
              }}
              x={"time"}
              y={"electricity"}
              cornerRadius={2}
              barRatio={0.2}
            />
```

**Comment by boygirl** [comment]
@Juli0GT 

try something like this:
```
<VictoryBar
              data={[
                { x: 1, y: 2 }, { x: 2, y: 2 }, { x: 3, y: 1 }, { x: 4, y: 4 } { x: 5, y: 3 } ...
              ]}
              style={{
                data: {
                  fill: (d) => d.x > 4 ? "red" : "blue",
                }
              }}
              cornerRadius={2}
              barRatio={0.2}
            />
```
