### ISSUE TITLE
stacked data should account for the x value of previous datasets

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory-bar#83]
are stacked bars suppose to look like the image bellow for more that one data point? or am I passing data incorrectly? do note that the picture is from: http://victory.formidable.com/docs/victory-bar
<img width="1112" alt="screen shot 2016-01-14 at 9 31 42 pm" src="https://cloud.githubusercontent.com/assets/6519974/12346137/8c7b6e5e-bb06-11e5-9e45-61a079d00419.png">

The data looks as follows: 
```javascript
var data = {[
    [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3}
    ],
    [
      {x: 1, y: 2},
      {x: 2, y: 1},
      {x: 3, y: 1}
    ],
    [
      {x: 1, y: 3},
      {x: 2, y: 4},
      {x: 3, y: 2}
    ],
    [
      {x: 4, y: 1},
      {x: 5, y: 2},
      {x: 6, y: 3}
    ],
    [
      {x: 4, y: 2},
      {x: 5, y: 1},
      {x: 6, y: 1}
    ],
    [
      {x: 4, y: 3},
      {x: 5, y: 4},
      {x: 6, y: 2}
    ],
  ]};
```

essentially I want to accomplish something like this: 
<img src="http://betterevaluation.org/sites/default/files/2d_StackedColumnChart2.png">

The plotting looks really odd unless I'm missing something? it actually looks the same as the first image when I instantiate VictoryBar in my React component.

**Comment by stephenotalora** [comment]
Does VictoryBar also stack (when prop stacked === true) the next set of data points on the y axis? If so is there any way to prevent this?

**Comment by boygirl** [comment]
Hi @stephenotalora, the component is trying to stack each series on top of the next.  If your data was instead:

```
[
  [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3},
      {x: 4, y: 1}, 
      {x: 5, y: 2},
      {x: 6, y: 3}
    ], 
  [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3},
      {x: 4, y: 1}, 
      {x: 5, y: 2},
      {x: 6, y: 3}
    ]
...
]
```
it would behave as expected. Is it the case that your later data needs to belong to a different series, and be colored differently?  If so, I hadn't considered that.  I'll add a bug label

**Comment by stephenotalora** [comment]
Thanks @boygirl I also added the same issue here as I thought I was going crazt while plotting my data: https://github.com/FormidableLabs/victory/issues/171 (this is a duplicate of victory-bar plotting issue #171) for your reference and there is some discussion going on on that thread.

**Comment by knowbody** [comment]
bringing this from https://github.com/FormidableLabs/victory/issues/171:

> looking at this issue there are a few more things that I found:
- https://jsbin.com/tudezagesa/edit?js,output (this should display 3 bars and have 3 bars stacked on top of each other) - displays 2 only
  - similar thing happens here - https://jsbin.com/cusulogupi/edit?js,output

> - https://jsbin.com/vibekupugo/1/edit?js,output (this should display 3 groups of 3 bars in each group) - nothing displayed, even though the *y values* are 1, not 0

**Comment by dandelany** [comment]
re @boygirl 's comment - I think the expected behavior in this particular case should be: if any of the data series are missing X-values that are present in other data series, the bar chart should act like they aren't missing, but instead just have zero values.

That is, [this](https://jsfiddle.net/dandelany/9ez47uam/) should render the same as [this](https://jsfiddle.net/dandelany/uoqxcr04/)

**Comment by boygirl** [comment]
@dandelany yep, we're on the same page.

**Comment by stephenotalora** [comment]
@boygirl @dandelany is there a new way to pass data to victory Bar? since https://github.com/FormidableLabs/victory-bar/pull/94? all victory bars appear to be rendering data incorrectly.

**Comment by dandelany** [comment]
@stephenotalora #94 hasn't landed in master or been released yet, and it should be backwards-compatible when it is released, so that shouldn't cause you any problems. Can you post an example?

**Comment by stephenotalora** [comment]
since 0.3.0 passing a blob of data as: 
```json
[[{"x":0,"y":8},{"x":1,"y":1},{"x":2,"y":2},{"x":3,"y":8},{"x":4,"y":8},{"x":5,"y":4},{"x":6,"y":7},{"x":7,"y":7},{"x":8,"y":6},{"x":9,"y":4},{"x":10,"y":2},{"x":11,"y":3},{"x":12,"y":1},{"x":13,"y":1},{"x":14,"y":2},{"x":15,"y":8},{"x":16,"y":7},{"x":17,"y":2},{"x":18,"y":7},{"x":19,"y":3},{"x":20,"y":1},{"x":21,"y":1},{"x":22,"y":7},{"x":23,"y":6},{"x":24,"y":6},{"x":25,"y":6},{"x":26,"y":6},{"x":27,"y":3},{"x":28,"y":1},{"x":29,"y":3},{"x":30,"y":2},{"x":31,"y":7},{"x":32,"y":3},{"x":33,"y":8},{"x":34,"y":3},{"x":35,"y":8},{"x":36,"y":6},{"x":37,"y":1},{"x":38,"y":2},{"x":39,"y":5},{"x":40,"y":3},{"x":41,"y":1},{"x":42,"y":1},{"x":43,"y":2},{"x":44,"y":8},{"x":45,"y":3},{"x":46,"y":1},{"x":47,"y":3},{"x":48,"y":4},{"x":49,"y":2},{"x":50,"y":6},{"x":51,"y":7},{"x":52,"y":8},{"x":53,"y":7},{"x":54,"y":1},{"x":55,"y":3},{"x":56,"y":5},{"x":57,"y":7},{"x":58,"y":6},{"x":59,"y":3},{"x":60,"y":6},{"x":61,"y":2},{"x":62,"y":2},{"x":63,"y":5},{"x":64,"y":1},{"x":65,"y":7},{"x":66,"y":1},{"x":67,"y":7},{"x":68,"y":1},{"x":69,"y":4}],[{"x":0,"y":10},{"x":1,"y":3},{"x":2,"y":4},{"x":3,"y":10},{"x":4,"y":10},{"x":5,"y":6},{"x":6,"y":9},{"x":7,"y":9},{"x":8,"y":8},{"x":9,"y":6},{"x":10,"y":4},{"x":11,"y":5},{"x":12,"y":3},{"x":13,"y":3},{"x":14,"y":4},{"x":15,"y":10},{"x":16,"y":9},{"x":17,"y":4},{"x":18,"y":9},{"x":19,"y":5},{"x":20,"y":3},{"x":21,"y":3},{"x":22,"y":9},{"x":23,"y":8},{"x":24,"y":8},{"x":25,"y":8},{"x":26,"y":8},{"x":27,"y":5},{"x":28,"y":3},{"x":29,"y":5},{"x":30,"y":4},{"x":31,"y":9},{"x":32,"y":5},{"x":33,"y":10},{"x":34,"y":5},{"x":35,"y":10},{"x":36,"y":8},{"x":37,"y":3},{"x":38,"y":4},{"x":39,"y":7},{"x":40,"y":5},{"x":41,"y":3},{"x":42,"y":3},{"x":43,"y":4},{"x":44,"y":10},{"x":45,"y":5},{"x":46,"y":3},{"x":47,"y":5},{"x":48,"y":6},{"x":49,"y":4},{"x":50,"y":8},{"x":51,"y":9},{"x":52,"y":10},{"x":53,"y":9},{"x":54,"y":3},{"x":55,"y":5},{"x":56,"y":7},{"x":57,"y":9},{"x":58,"y":8},{"x":59,"y":5},{"x":60,"y":8},{"x":61,"y":4},{"x":62,"y":4},{"x":63,"y":7},{"x":64,"y":3},{"x":65,"y":9},{"x":66,"y":3},{"x":67,"y":9},{"x":68,"y":3},{"x":69,"y":6}]];
```

which is the same data structure as: 
[
  [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3},
      {x: 4, y: 1}, 
      {x: 5, y: 2},
      {x: 6, y: 3}
    ], 
  [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3},
      {x: 4, y: 1}, 
      {x: 5, y: 2},
      {x: 6, y: 3}
    ]
...
]

will produce: 
![screen shot 2016-01-29 at 5 12 34 pm](https://cloud.githubusercontent.com/assets/6519974/12692302/10a9b29a-c6aa-11e5-9bc6-9208fe2b86f6.png)

something happening with the domain of the chart since 0.3.0? it appears to be stacking but the domain is not following the axis range:  {x:[0, 20], y:[0,20]}

note the graphs will never go beyond this domain in either axis

**Comment by stephenotalora** [comment]
so width and height need to be over a 1000px for the bars to render with enough space. victory-line doesn't appear to have this issue

**Comment by boygirl** [comment]
@stephenotalora the problem you're seeing above I think is only layout related. For grouped bars, the center bar in each group is scaled to a position on the x axis, and then the group of bars is laid out around it based on the `width` and `padding` attrs on the style object, like so: 

```
style={{
  data: { width: 8, padding: 2 ...}
}}
```
So I think what you're seeing is just groups of bars being rendered over each other. We don't have automatic width setting for grouped bars yet, but it's on our list: https://github.com/FormidableLabs/victory-bar/issues/73. In the meantime you could try playing with the `width` and `padding` properties described above. I hope that helps! P.S. #94 is landing as we speak :)

**Comment by stephenotalora** [comment]
Thanks @boygirl! I will give that a try, I did change the (Radium) margin and the paddingDomain from 1 to 0. on my dev env it seemed to have been okay but on prod build something wrong happened, I will try to look into padding and see if something changed. I can't vpn to my source code at the moment but I will get back with findings on Monday while I do some more debugging. 

By the way thanks for the fantastic support! I'll be keeping an eye open on the npm registry for https://github.com/FormidableLabs/victory-bar/pull/94

**Comment by stephenotalora** [comment]
@boygirl, after some debugging looks like the problem is with the scale prop in VictoryBar. how should one pass the actual d3.scale? per documentation I tried: 
`d3Scale.time(), {x: d3Scale.linear(), y: d3Scale.log()}` (d3.scale.linear(), d3.scale.log() etc...) and this seems to scale the width to something less than 300px while height is still normal.

**Comment by boygirl** [comment]
@stephenotalora the scale prop can be passed in as a d3 scale, or as a string corresponding to a named d3 scale, so the following should all be valid:
```
scale={"linear"}
scale={{x: "time", y: "log"}}
scale={d3Scale.linear()}
scale={{y: d3Scale.log()}}
...
```
I'm very confused about the scale effecting the width... Can you repro your problem in a jsfiddle?

**Comment by stephenotalora** [comment]
Hi @boygirl, yep. I can repro. you can have a look at https://jsfiddle.net/stephenota/85pcbgo2/

you can swap victory version between: 
https://npmcdn.com/victory@0.4.0/dist/victory.min.js
and going way back to say: 
https://npmcdn.com/victory@0.1.1/dist/victory.min.js

You can see how differently the two behave. so the question is what changed?

**Comment by boygirl** [comment]
We switched from `d3` to using only the modules we need like `d3-scale`. Check this out: https://jsfiddle.net/nbbk6jLd/. 
specifying `scale={"linear"}` applies `d3Scale.linear()` from the `d3-scale` module. `d3-scale` and `d3.scale` _shouldn't_ behave differently. very weird

**Comment by stephenotalora** [comment]
Thanks @boygirl! I'm switching to Strings rather than returning d3 functions to reuse what is already implemented in Victory for d3 scales. this should resolve differences as shown in your fiddle.

**Comment by stephenotalora** [comment]
nvm found what I was looking for.
/**
     * The scale prop determines which scales your chart should use. This prop can be
     * given as a string specifying a supported scale ("linear", "time", "log", "sqrt"),
     * as a d3 scale function, or as an object with scales specified for x and y
     * @exampes d3Scale.time(), {x: "linear", y: "log"}
     */
