### ISSUE TITLE
incorrectly displayed bars

### ISSUE THREAD

**Issue by knowbody** [FormidableLabs/victory-bar#85]
Based on the discussion https://github.com/FormidableLabs/victory-bar/issues/83 I found these few bugs:

- https://jsbin.com/tudezagesa/edit?js,output (this should display 3 bars and have 3 bars stacked on top of each other) - displays 2 only
  - similar thing happens here - https://jsbin.com/cusulogupi/edit?js,output

- https://jsbin.com/vibekupugo/1/edit?js,output (this should display 3 groups of 3 bars in each group) - nothing displayed, even though the *y values* are 1, not 0

**Comment by boygirl** [comment]
Based on the jsbins, these issues look to be solved.
