### ISSUE TITLE
scale factor on x and y coords

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory-bar#86]
Hi Fomiddable team - 
Based on the documentation [here](http://victory.formidable.com/docs/victory-bar) you can specify the scale factor by using the scale prop. Is there away to register to a callback to retrieve the current ***calculated scale factor*** for any of the coordinates or ideally one for each?

**Comment by boygirl** [comment]
@stephenotalora the scale here means a d3 scale function, not a scale value. We don't currently have any plans for exposing that in a callback, as it is a supplied prop to begin with. We _are_ planning on providing the data point and actual coordinates in our general interactivity support feature coming (hopefully) by the end of this month
https://github.com/FormidableLabs/victory/blob/master/ROADMAP.md

This feature will allow you to attach event handlers to elements. Whatever handlers you attach will have access to data and coordinates.
